/**
 * Constructs a safe direct Telegram link for a job item
 */
export const getJobTelegramUrl = (job) => {
  if (!job) return "#";

  // 1. Direct post URL generated by backend
  if (job.postUrl) {
    return job.postUrl;
  }

  // 2. Fallback: Construct URL if messageId & channelUsername exist
  if (job.channelUsername && job.messageId) {
    const cleanUsername = job.channelUsername.replace("@", "");
    return `https://t.me/${cleanUsername}/${job.messageId}`;
  }

  // 3. Fallback: Channel home link if messageId is missing
  if (job.sourceName && job.sourceName.startsWith("@")) {
    const cleanUsername = job.sourceName.replace("@", "");
    return `https://t.me/${cleanUsername}`;
  }

  // 4. Default fallback
  return "https://t.me";
};